on: 
  push:
    branches:
      - main

name: ðŸš€ Deploy build para o servidor

jobs:
  web-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: ðŸš€ Deploy via FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: dev.iscon.edu.br
          username: user_ftp@dev.iscon.edu.br
          password: user_ftp@pass
          protocol: ftps
          port: 21
          server-dir: ./
          dangerous-clean-slate: false
